/**
 * Generador de documentación OpenAPI para el framework API SDK
 * Componente: lib/utils/openapiGenerator.js
 */

class OpenApiGenerator {
  /**
   * Constructor del generador de OpenAPI
   * @param {Object} options - Opciones de configuración
   * @param {string} options.title - Título de la API
   * @param {string} options.description - Descripción de la API
   * @param {string} options.version - Versión de la API
   * @param {Array} options.servers - Servidores donde se aloja la API
   */
  constructor(options = {}) {
    this.spec = {
      openapi: '3.0.0',
      info: {
        title: options.title || 'API Documentation',
        description: options.description || 'Generated by API SDK Framework',
        version: options.version || '1.0.0'
      },
      servers: options.servers || [{ url: 'http://localhost:3000' }],
      paths: {},
      components: {
        schemas: {},
        securitySchemes: {}
      }
    };
  }

  /**
   * Agrega una ruta a la documentación OpenAPI
   * @param {Object} route - Definición de la ruta
   * @param {string} route.path - Ruta del endpoint
   * @param {string} route.method - Método HTTP
   * @param {Object} route.config - Configuración del endpoint
   */
  addRoute(route) {
    const { path, method, config = {} } = route;
    
    if (!this.spec.paths[path]) {
      this.spec.paths[path] = {};
    }
    
    this.spec.paths[path][method.toLowerCase()] = {
      summary: config.summary || '',
      description: config.description || '',
      parameters: config.parameters || [],
      requestBody: config.requestBody,
      responses: config.responses || {
        '200': {
          description: 'Operación exitosa'
        }
      },
      security: config.security || []
    };
  }

  /**
   * Agrega un esquema a la documentación
   * @param {string} name - Nombre del esquema
   * @param {Object} schema - Definición del esquema
   */
  addSchema(name, schema) {
    this.spec.components.schemas[name] = schema;
  }

  /**
   * Agrega un esquema de seguridad
   * @param {string} name - Nombre del esquema de seguridad
   * @param {Object} scheme - Definición del esquema de seguridad
   */
  addSecurityScheme(name, scheme) {
    this.spec.components.securitySchemes[name] = scheme;
  }

  /**
   * Agrega un requisito de seguridad global
   * @param {Array} securityRequirement - Requisitos de seguridad
   */
  addGlobalSecurity(securityRequirement) {
    if (!this.spec.security) {
      this.spec.security = [];
    }
    this.spec.security.push(securityRequirement);
  }

  /**
   * Genera la especificación OpenAPI completa
   * @returns {Object} - Especificación OpenAPI
   */
  generateSpec() {
    return this.spec;
  }

  /**
   * Agrega rutas de documentación OpenAPI al servidor
   * @param {Object} server - Instancia del servidor
   */
  addDocumentationRoute(server) {
    // Ruta para obtener la especificación OpenAPI en formato JSON
    server.addRoute('GET', '/openapi.json', (req, res) => {
      const spec = this.generateSpec();
      res.writeHead(200, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify(spec, null, 2));
    });

    // Ruta para la documentación interactiva con Swagger UI
    server.addRoute('GET', '/docs', (req, res) => {
      const swaggerHtml = `
<!DOCTYPE html>
<html>
<head>
  <title>API Documentation</title>
  <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@latest/swagger-ui.css" />
</head>
<body>
  <div id="swagger-ui"></div>
  <script src="https://unpkg.com/swagger-ui-dist@latest/swagger-ui-bundle.js"></script>
  <script>
    SwaggerUIBundle({
      url: '/openapi.json',
      dom_id: '#swagger-ui',
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.presets.standalone
      ]
    });
  </script>
</body>
</html>`;
      
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.end(swaggerHtml);
    });
  }
}

module.exports = OpenApiGenerator;